name: Push to Docker registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        debian: ["buster", "bullseye"]
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image
      run: docker build . --file ${{ matrix.python }}-${{ matrix.debian }}-build/Dockerfile.arm32v7 --tag mshr-h/onnx-raspberry-pi-3:${{ matrix.python }}-${{ matrix.debian }}-build
